server:
  port: 8040

spring:
  data:
    mongodb:
      username: keerthi
      password: keerthi
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafak:
    consumer:
      bootstrap-services: localhost:9092
      group-id: paymentGroup,OderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: '*'
        spring.son.type.mapping: orderConfirmation:com.kss.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.kss.notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: alibou
    password: alibou
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000